### ISSUE TITLE
Implement avatar functionality

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#11]
- Users should be able to select his avatar
- Avatar will be selected randomly 
- Avatar setup should be saved at database

**Comment by adawolfs** [comment]
- Users should be able to select his avatar

**Comment by Jhonproyec** [comment]
I worked on the design of the view to edit the user's profile, I was researching and reading the source code of the example of the avatars to be able to show an avatar when the button is clicked to generate one.
the button operation remains to be programmed.
Completion time approximately 2 hours

**Comment by Jhonproyec** [comment]
I worked on implementing the button so that the avatars would be shown randomly, also in the menu and on the user profile screen the name of the registered user is shown, and his email.
I started working on editing the profile, obtaining the user's data, such as their profile name.
Completion time approximately 5 hours

**Comment by Jhonproyec** [comment]
I worked on implementing the avatars, when the user wants to change the avatar of his profile photo, a code is generated to be able to show the avatar and that code is saved in the database, the user can also edit his profile name.
I worked in that when the user registers an avatar is added as a profile photo automatically, saving that avatar's code in the database.
I modified the posts so that the avatar of the user who made the publication is shown, and also the comments.
Completion time approximately 5 hours

**Comment by Jhonproyec** [comment]
I worked on solving the problem that when hovering the mouse on the button to load an avatar, the avatar image was cut off.
Completion time 2 hours

**Comment by Jhonproyec** [comment]
I worked on solving the problems of showing the avatar.
I had problems with the ávatars that appear in the posts, since they always appear cut off, they do not appear complete, I was looking for how to solve it and the way I found is to put more padding on the left side, that affects the style of the posts. completion time 2 hours and 30 minutes
