### ISSUE TITLE
Implement Theme

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#12]
https://flutter.dev/docs/cookbook/design/themes
https://api.flutter.dev/flutter/material/Theme-class.html

https://www.youtube.com/watch?v=HSAa9yi0OMA

**Comment by Jhonproyec** [comment]
I worked on implementing the light and dark themes to the application, I read the documentation to be more clear about the operation of themas in flutter, I also saw the suggested video and took a reference from that video to implement the themes in the application.
completion time 2 hour and 30 minutes

**Comment by Jhonproyec** [comment]
I worked on the implementation and functionality of the button to change the themes from light to dark, I looked for a better implementation so as not to write so many lines of code, but the best option was the one suggested in the video.
I had problems with the color change of the letters and icons, and I was investigating how to solve it.
I also had problems with the routes, since when implementing the materialApp the routes did not work well and I spent time trying to fix it.
Completion time approximately 5 hours

**Comment by Jhonproyec** [comment]
I worked on implementing the light and dark theme to the application, I had problems displaying the text well, and I was working on that today, I also had problems changing the color to the ShowModalbuttonseet, I had to do some research to be able to fix the colors problems and I was able to work it out. I also made small details like changing the color of the icons and the title of the appbarr
Completion time approximately 5 hours

**Comment by Jhonproyec** [comment]
I worked on solving small details of the implementation of the dark theme, I added the setting screen and added the button there to change the theme from light and dark, I corrected the errors to implement the thema in the code.
Completion time approximately 5 hours

**Comment by Jhonproyec** [comment]
I worked on ordering the code of the file where the styles of the application are, investigating I realized that the texts have their properties, as well as the buttons and inputs, I read the code that I had implemented and I rewritten it doing it in a more understandable way . completion time 1 hour and 30 minutes approximately
