### ISSUE TITLE
Validate if image is selected before create post

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#20]

**Comment by Jhonproyec** [comment]
I worked to validate if the user had uploaded an image to publish the post, I had problems with the definitions of variables, since errors appeared, and some because of how the images were being loaded.
Completion time 3 hours approximately

**Comment by Jhonproyec** [comment]
I worked on the validation to create a post without the image, uploading only the text of the post, I had problems at first since I was not uploading the description of the post and only the image was uploaded, I solved it and I was working on how to show the post without the image, Time of realization 2 hours and 30 minutes

**Comment by Jhonproyec** [comment]
The user can make a publication without an image, I was working on the validation at the time of displaying the image, and I corrected the spaces between the elements so that the publication looks good with an image and without an image, completion time approximately 2 hours
