### ISSUE TITLE
Enable comment deletion

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#27]
Users should be able to delete his own comments

**Comment by Jhonproyec** [comment]
I worked on the integration of the delete comments button, the comments cannot be deleted yet, since there is not still an ID selected for each of them. completion time approximately 2 hours.
I had problems trying to remove them, since I wanted to access the comment id for they are not yet being generated.

**Comment by Jhonproyec** [comment]
I worked on the functionality of the delete comment button, making the button appear only in the comment that the user made.
Completion time 2 hours and 30 minutes approximately

**Comment by Jhonproyec** [comment]
I worked on the implementation of the delete comments button, I had problems deleting a specific comment, since it deleted all the comments.
Completion time approximately 2 hours

**Comment by Jhonproyec** [comment]
I worked on programming the delete comment button.
At first I had problems since I was only deleting the comment from the array that the database returns, but I was not deleting it from the database, so I decided to edit the database and so I was able to delete the comment, in the meeting that had support so that the changes are noticed without the need to refresh the page. Time of realization 2 hours approximately
