### ISSUE TITLE
Filter posts by event

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#28]
Events should show only posts made during and into that event

**Comment by Jhonproyec** [comment]
I worked on filtering the posts by the events created,
I was researching a form of validation so that the user cannot enter the home if they have not selected an event
realization time approximately 2 hours

**Comment by Jhonproyec** [comment]
I worked on displaying the posts for the events.
at first I had problems since I put the emit inside the foreach and I was saving only one post, then I decided to save the posts in a new list and add that list to the state outside the foreach and thus it showed me all the posts.
Completion time approximately 2 hours
