### ISSUE TITLE
Update Register Style

### ISSUE THREAD

**Issue by GuateGeeks** [GuateGeeks/GeeksDayFlutter#3]

**Comment by Jhonproyec** [comment]
I worked on the layout of the registration form.
Completion time approximately 1 hour.

**Comment by Jhonproyec** [comment]
I worked on the new design of the registration form.
I read the code to understand how the validations were made and how the data was sent.
I did the corresponding tests to see that the validations worked.
Completion time 5 hours.
I had problems with the password inputs, since when you want to see the password that is being written, they are not shown.
I was investigating the error and doing several tests but the result was the same.

**Comment by Jhonproyec** [comment]
I worked on solving the problem of showing the password and hiding it, I also created a folder to save the inputs and thus reuse them in the login
Time of realization 3 hours approximately.
I had problems with passing the parameters of the inputs to do the validation, I consulted a meeting to be able to solve the problem and that's how it was done.
