### ISSUE TITLE
Admin metrics view

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#30]
- Users with higher score on quizzes
- Users with most posts
- Users with most likes
- Users with most comments

**Comment by Jhonproyec** [comment]
I worked on the view and on implementing the logic for the administration of the application.
I had problems to send certain parameters to the post_cubit, but in the meeting it was decided to create files that are only related to the administration of the application and the problem was solved.
Completion time approximately 5 hours

**Comment by Jhonproyec** [comment]
I worked on the implementation of the administrator metrics, I had problems with displaying the data on the screen, and I was investigating how to solve it.
Completion time approximately 5 hours

**Comment by Jhonproyec** [comment]
I worked on the functionality of the select button.
I had a problem to show the information of the posts but in the meeting it was solved and the information can now be displayed.
Completion time 2 hours and 30 minutes approximately

**Comment by Jhonproyec** [comment]
I concentrated on working and showing the users who have liked the posts the most and showing them using the hashmap function as recommended to me in today's meeting.
Time of realization 2 hours

**Comment by Jhonproyec** [comment]
I worked on showing the users who have published the most post, who have given the most like and who have commented the most.
completion time 3 hours and 30 minutes

**Comment by Jhonproyec** [comment]
I worked on showing the information of the users, and also on adding the options to the select to show the information, I was investigating how I could assign values ​​to the enum constants, but they could not assign values, in a meeting they suggested I create a map and thus to be able to show well the options in the select, time of realization 2 hours and 30 minutes

**Comment by Jhonproyec** [comment]
I worked on the select to show the students that the most posts, likes or comments have been made.
I had problems for the selected category to stay fixed in the select part, but it threw an error, that the data was not defined in the same way, I defined all the variables in the same way but it always threw me the same error.
Completion time 2 hours and 30 minutes

**Comment by Jhonproyec** [comment]
I worked on implementing the button so that it shows the users who have had the most correct answers answering the quizzes, completion time 1 hour and 30 minutes approximately
