### ISSUE TITLE
Rediseño de Feed

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#62]
https://github.com/GuateGeeks/GeeksDayFlutter/issues/59

**Comment by Jhonproyec** [comment]
I worked on the redesign of the feed in the light theme I moved the navigation button to the right side and I placed the guategeeks logo, I had problems with the gradient in the buttons since in the Data theme you can not create gradients, so I created a widget customized to be able to carry the gradient colors there.
completion time approximately 3 hours

**Comment by Jhonproyec** [comment]
I worked on the redesign of the dark theme to show the post, realization time 1 hour approximately

**Comment by adawolfs** [comment]
Based on design revision:
```
para el corazón activo sugiero que se coloque este código de color, va mas con la paleta utilizada #C852FF
en el menú de configación propuso utilizar un gris claro #D6D6D6 para los textos e íconos en modo oscuro
para el modo claro se sugiere usar este color #767676 para iconos y textos
para los íconos y en general se utilizarra un degrade lineal de #4B3BAB (morado) a #0E89AF (celeste)
```

**Comment by Jhonproyec** [comment]
I updated the feed colors according to those specified in the comment. realization time 1 hour approximately

**Comment by Jhonproyec** [comment]
I worked on the redesign of the feed to show the posts, I changed the colors of the progress bars of the quiz, I also changed the color of the like icon when the user likes a post, and I was reviewing why the avatars are shown incomplete, I wanted to help the widget inspector tool, but at the time of activating it the avatars are shown complete. realization time 2 hours and 30 minutes approximately

**Comment by Jhonproyec** [comment]
I worked on the redesign of the page where the posts are displayed, I had problems with the like and comment icons, since I could not add them as svg, and I added them as a png image. realization time approximately 3 hours

**Comment by adawolfs** [comment]
which kind of problems did you had with svg?

**Comment by Jhonproyec** [comment]
I worked on adding the likes and comments icons as svg image also changedé the source size for the post, realization time 2 hours approximately

**Comment by Jhonproyec** [comment]
I worked on the redesign of the feed, I added the shading at the bottom of the images, I also corrected the width of the progress bars of the quiz answers, I had problems when correcting it because it gave me an error that the width was undefined, I deleted the row widget to be able to correct that error and thus the progress bar occupies the entire width, completion time approximately 2 hours

**Comment by adawolfs** [comment]
Que tal @Jhonproyec note que los iconos de like y comment no estan alineados al borde de la imagen del post tal y como se muestra en el diseño, voy a solicitar que nos pongan en el diseño un ejemplo con texto tambien.


![2022-02-10 11_28_50-GeeksDay - Brave](https://user-images.githubusercontent.com/7836423/153463042-72b48477-c741-4e97-9ff0-75607e9cb0f5.png)

**Comment by Jhonproyec** [comment]
I worked on aligning the icons with the image and text.
completion time approximately 20 minutes

**Comment by adawolfs** [comment]
Closed by Merge

**Comment by Jhonproyec** [comment]
I worked exchanging like and comment icons with the content of the post, I centered the username and date of creation of the post, and also the button to show the options of the post, I had problems with the button to show the options of the post, since it comes with a default padding and it wouldn't align by removing it, I solved it by adding the Aling widget. completion time approximately 2 hours

**Comment by Jhonproyec** [comment]
viewing the application on mobile the button to show the options on mobile does not have the same margins that are applied to it on the web.
