### ISSUE TITLE
Rediseño listado de comentarios

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#66]
https://github.com/GuateGeeks/GeeksDayFlutter/issues/59

**Comment by Jhonproyec** [comment]
I worked on the redesign of the comments view, completion time approximately 1 hour

**Comment by Jhonproyec** [comment]
I worked on the redesign of the comments, I had problems with the avatars, since adding the like icon in the post description cuts it off, and I was reviewing it, I was also seeing how to create the dotted line to divide the post description with the comments.
I left the comments and description of the post on the left side, because if I leave it on the same side as the name and date when the comment or description of the post is too long, it doesn't look good.
completion time approximately 2 hours

**Comment by adawolfs** [comment]
Please add the margin at the left of the comment

**Comment by Jhonproyec** [comment]
I worked on the redesign of the comments, I had problems when implementing the svg icons in the comments, since when I liked or unliked the change was not shown on the main page where the posts are displayed.
Completion time approximately 2 hours

**Comment by Jhonproyec** [comment]
I checked the input color of the comments and in dark and light mode the text was visible, I just had to adjust how many lines could be shown in the input.
completion time approximately 20 minutes

**Comment by adawolfs** [comment]
Closed by merge
