### ISSUE TITLE
Design and Implement "Post -> Comments" Relationship

### ISSUE THREAD

**Issue by GuateGeeks** [GuateGeeks/GeeksDayFlutter#7]

**Comment by Jhonproyec** [comment]
I worked on the design of the comments view, the user when pressing the comment button, the application will send him to a page where all the comments of the post are displayed and he can make his comment. Completion time 1 hour and 45 minutes.

I also worked on the avatar for the users, but I had problems implementing them, since when I wanted to see the avatars it only showed me the svg code, I tried to solve it, but the result was the same, and the documentation is not so clear to guide me .
Completion time 3 hours approximately

**Comment by Jhonproyec** [comment]
I worked on finishing the design of the comment view, also added a textformfield at the bottom of the screen so that the user can write their comment, completion time 1 hour 45 minutes.
I was also investigating how to implement the avatars to the application but I had the same problem, it only showed the svg code on the screen, in the meeting the problem was resolved and the avatars were implemented to the application, completion time 3 hours and 45 minutes approximately

**Comment by Jhonproyec** [comment]
I worked on changing the way the date is displayed when a comment is made, I made some changes to be able to reuse the function that displayed the post creation date.
Completion time approximately 1 hour
