### ISSUE TITLE
Improve performance on Mobile devices 

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#71]
The applications feels slow on mobile devices specially on feed list.

**Comment by Jhonproyec** [comment]
I checked why the application on mobile devices feels slow when scrolling, and it is because of the scrollController, by removing that function the application was more fluid, but I am using the scrollController to be able to show the button to go up in the application time of realization 2 hours approximately

**Comment by adawolfs** [comment]
Is it done?

**Comment by adawolfs** [comment]
@Jhonproyec

**Comment by Jhonproyec** [comment]
The fluidity of the mobile application is quite good
