### ISSUE TITLE
Fix profile edition navigation

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#76]
After the profile is updated the user should be redirected to the profile

**Comment by Jhonproyec** [comment]
I worked on correcting the error when editing the user profile, but looking at the design of the application, the editUser screen does not exist, so I decided to start with the redesign of the user page and not spend time on correcting the error, completion time 1 hour and 30 minutes approximately
this issue will be fixed in ticket #67
