### ISSUE TITLE
Implement routes

### ISSUE THREAD

**Issue by adawolfs** [GuateGeeks/GeeksDayFlutter#79]
@Jhonproyec please add the link to the package

**Comment by Jhonproyec** [comment]
package to have a better control of routes in the application
https://pub.dev/packages/get_it

**Comment by Jhonproyec** [comment]
for the implementation of the routes this library will be used, since following the course of web flutter this library is much simpler to implement and is the most recommended
https://pub.dev/packages/fluro

**Comment by adawolfs** [comment]
Please evaluate redirect the user to a classic html page in order to implement complex functionality with JavaScript libraries.

It should be nice to fully load html and JS embedded into flutter.

**Comment by Jhonproyec** [comment]
I worked on implementing the routes, I had problems at first to display the content, I had to analyze how to implement it in the application so that the routes would work well.
For now, when pressing the return button on the browser or on the phone, it is only working on the login, registration and events pages, the routes for the posts need to be implemented.
completion time 2 hours and 30 minutes approximately.
I am using both libraries, fluro and get it.
fluro to manage the routes and send parameters, I use get it to save the state of the application and thus when pressing the return button of android or the browser, the application does not close

**Comment by Jhonproyec** [comment]
I worked on the implementation of routes, most of the application already has routes integrated, I still need to implement the route for the image, and comments. completion time 1 hour and 45 minutes approximately

**Comment by adawolfs** [comment]
Hello @Jhonproyec I like how it works, I'm curious about the MainDrawer use, could you please share it with me?

⚠️ Please be careful when adding files, seems like you have pushed a "test" file into the repo.
https://github.com/GuateGeeks/GeeksDayFlutter/blob/c24bb6f01b8865ec135f99ffd8c18d1b3c5bda2f/lib/bloc/posts/post_test_cubit.dart

**Comment by Jhonproyec** [comment]
I worked on the implementation of routes, I was investigating to obtain a post by id to be able to show the comments and the image when clicking on it. completion time 2 hours

**Comment by Jhonproyec** [comment]
I worked on finishing the routes implementation for the pages that were being used at the time of the feature/routes branch creation. I had trouble implementing the comments route, as I had to fetch a single post from the database, and had to figure out how to fetch it.
At the moment when making a comment or liking a publication the application costs to load but that will be resolved in the ticket #93 
completion time 2 hours and 30 minutes approximately

**Comment by adawolfs** [comment]
Implementation done
