### ISSUE TITLE
Design and Implement "Post deletion"

### ISSUE THREAD

**Issue by GuateGeeks** [GuateGeeks/GeeksDayFlutter#8]
Only post owner will be able to delete it.

**Comment by adawolfs** [comment]
A validation for this needs to be implemented.

A method bool isDeletable funcion  should be implemented
A method bool ownedByUser function should be implemented
https://github.com/GuateGeeks/GeeksDayFlutter/blob/development/lib/bloc/post_cubit.dart

A method postDeletion should be implemented, deletion should validate user owner as well
https://github.com/GuateGeeks/GeeksDayFlutter/blob/development/lib/services/post_service.dart

**Comment by Jhonproyec** [comment]
Implement the Delete Post action button.
I had problems at the beginning of the implementation, since when I tried to run the application it told me that the Widget needed a parent widget, but I managed to solve it.
The options that appear when the button is clicked are defined in an array. If you want to create a new option, just add it to that list.
Completion time approximately 4 hours.

**Comment by Jhonproyec** [comment]
I worked on the functionality of the delete button.
The delete option will appear only to the user who created the post.
Completion time 2 hours and 30 minutes.
